/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      '學習課程': [
        'intro', 
        'create', 
        'addfile',
        'pages',
        'local',
        'vsc',
        'howto',
        'credits',
      ],
    },
    {
      type: 'category',
      label: '資源連結',
      items: [
        {
          type: 'link',
          label: 'Markdown 文件',
          href: 'https://markdown.tw/',
        },
        {
          type: 'link',
          label: 'Writing on GitHub',
          href: 'https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github',
        },
        {
          type: 'link',
          label: 'Webcamp',
          href: 'https://www.jywglady.org/webcamp',
        },
        {
          type: 'link',
          label: 'HTML Tutorial',
          href: 'https://www.w3schools.com/html/',
        },
      ]
    },
  ],
};

module.exports = sidebars;
